require: []

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "gemfiles/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Exclude:
    - "lib/mailjunky/connection.rb"
    - "lib/mailjunky/rails/delivery_method.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/mailjunky/connection.rb"
    - "lib/mailjunky/rails/delivery_method.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/mailjunky/connection.rb"
    - "lib/mailjunky/rails/delivery_method.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/mailjunky/connection.rb"
    - "lib/mailjunky/rails/delivery_method.rb"

Metrics/ParameterLists:
  CountKeywordArgs: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 120
